%YAML:1.0
---

# ================= 预处理参数 =================
# 注意，设置 roi_zmin_target / roi_zmax_target 时，不要将 {0.0,0.0,0.0} 包含进来
# 注意，设置 roi_zmin_source / roi_zmax_source 时，不要将 {0.0,0.0,0.0} 包含进来
roi_xmin_target : -0.12
roi_xmax_target :  0.12
roi_ymin_target : -0.21
roi_ymax_target :  0.10
roi_zmin_target :  0.15
roi_zmax_target :  0.5

roi_xmin_source : -0.2
roi_xmax_source :  0.2
roi_ymin_source : -0.2
roi_ymax_source :  0.2
roi_zmin_source :  0.05
roi_zmax_source :  0.5


# ================= 粗匹配（FPFH + RANSAC）参数 =================
# 先确定 voxel_leaf_size，再确定 normal_radius，最后确定 fpfh_radius
# normal_radius 要比 voxel_leaf_size 大，一般是 voxel_leaf_size 的 2~4 倍
# fpfh_radius 要比 normal_radius 大，一般是 normal_radius 的 2~10 倍
voxel_leaf_size : 0.0030
normal_radius   : 0.0090
fpfh_radius     : 0.0195

ransac_max_iterations            : 40000
ransac_num_samples               : 3
ransac_correspondence_randomness : 50
ransac_similarity_threshold      : 0.87
ransac_max_corr_distance_factor  : 2.5
ransac_inlier_fraction           : 0.70


# ================= ICP 精配准参数 =================
# icp_max_corr_distance_factor：ICP 最大对应距离 = 该系数 * voxel_leaf_size
# icp_max_iterations           ：ICP 最大迭代次数
# icp_fitness_score_threshold  ：ICP 收敛后允许的最大 fitness，越小越严格
icp_max_corr_distance_factor : 2.0
icp_max_iterations           : 30
icp_fitness_score_threshold  : 0.005


# ================= 调试与路径 =================
debug_flag_str : "true"
#debug_flag_str : "false"

# 目标点云（全局点云）
# target_path : "E:/Robot/Project/Inuitive/Inuitive_data/r112scan/two_cam/global_face_1/face_m_pc_seg_2.ply"
# 源点云（局部点云）
# source_dir : "E:/Robot/Project/Inuitive/Inuitive_data/r112scan/two_cam/20251027_lh/"


target_path : "./test_data_2/pcd-1_m.ply"
source_dir : "./test_data_2/20251122_lh/"

