# 左相机标定配置

camera:
  matrix:
    fx: 776.847377473825986  # 焦距 fx
    fy: 776.847377473825986   # 焦距 fy
    cx: 780.077427821522292  # 主点 cx
    cy: 580.702099737532762  # 主点 cy
  distortion_coeffs: [0.00000, 0.000000, 0.00000, 0.00000, 0.00000]  # 畸变系数（假设无畸变）

chessboard:
  size: [19, 19]  # 棋盘格行列数
  square_size: 0.01  # 每个格子的物理尺寸（单位：米，1cm）
