# 右相机标定配置

camera:
  matrix:
    fx: 796.71317819559   # 焦距 fx
    fy: 796.8654201077464 # 焦距 fy
    cx: 820.2897077029871 # 主点 cx
    cy: 606.3543615788664 # 主点 cy
  distortion_coeffs: [-0.05127411767356332, 0.14767296723175963, 0.00014463666479695917, -0.0014685870176580002, -0.10910116165293914]  # 畸变系数（假设无畸变）

chessboard:
  size: [19, 19]  # 棋盘格行列数
  square_size: 0.01  # 每个格子的物理尺寸（单位：米）
