# 左相机标定配置

camera:
  matrix:
    fx: 776.847377473825986  # 焦距 fx
    fy: 776.847377473825986   # 焦距 fy
    cx: 780.077427821522292  # 主点 cx
    cy: 580.702099737532762  # 主点 cy
  distortion_coeffs: [0.00000, 0.000000, 0.00000, 0.00000, 0.00000]  # 畸变系数（假设无畸变）

calibration_board:
  type: 'aruco'  # 标定板类型：'aruco' 或 'circle_grid'
  dictionary: 'DICT_4X4_50'  # ArUco字典类型
  marker_length: 0.0211875  # 每个ArUco标记的边长（单位：米）
  board_size: [8, 4]  # 板子上的标记排列：[行数, 列数]
  square_size: 0.02825  # 标记之间的距离（单位：米，从标记中心到中心）
