# 右相机标定配置

camera:
  matrix:
    fx: 775.952503488026991   # 焦距 fx
    fy: 775.952503488026991 # 焦距 fy
    cx: 825.154450261780084 # 主点 cx
    cy: 601.070680628272271 # 主点 cy
  distortion_coeffs: [0.00000, 0.00000, 0.00000, 0.00000, 0.00000]  # 畸变系数（假设无畸变）

chessboard:
  size: [11, 8]  # 棋盘格行列数
  square_size: 0.015  # 每个格子的物理尺寸（单位：米，1cm）

camera: # 单位：毫米，需要转化为米
  sensor0: 
    type: 'DEPTH'
    Translation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    Rotation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    matrix:
      fx: 541.504178272980425
      fy: 510.000000000000000
      cx: 538.497214484679603
      cy: 360.000000000000000
    distortion_coeffs: [0.00000 , 0.00000 , 0.00000 , 0.00000 , 0.00000]

  sensor1:
    type: 'DEPTH'
    Translation: [25.08265191851344155793 , -0.00000000000013486857 , -0.00000000000001254552]
    Rotation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    matrix:
      fx: 541.504178272980425
      fy: 510.000000000000000
      cx: 538.497214484679603
      cy: 360.000000000000000
    distortion_coeffs: [0.00000 , 0.00000 , 0.00000 , 0.00000 , 0.00000]

  sensor2:
    type: 'RGB'
    Translation: [50.27391961437235323729 , 0.17586925255438673465 , 1.96659374947401510703]
    Rotation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    matrix:
    fx: 775.952503488026991   # 焦距 fx
    fy: 775.952503488026991   # 焦距 fy
    cx: 825.154450261780084   # 主点 cx
    cy: 601.070680628272271   # 主点 cy
    distortion_coeffs: [0.00000, 0.000000, 0.00000, 0.00000, 0.00000]  # 畸变系数（假设无畸变）
