# 左相机标定配置

camera:
  matrix:
    fx: 789.4456542637116  # 焦距 fx
    fy: 788.484033739993   # 焦距 fy
    cx: 777.0120061708291  # 主点 cx
    cy: 576.1858690267106  # 主点 cy
  distortion_coeffs: [-0.05273141350460728, 0.13791226924792835, -0.0017148210591245957, -0.0017385178282291324, -0.0920477881936919]  # 畸变系数（假设无畸变）

chessboard:
  size: [19, 19]  # 棋盘格行列数
  square_size: 0.01  # 每个格子的物理尺寸（单位：米，1cm）

robot_poses_file: "robot_pos.txt"  # 机器人位姿文件路径
image_folder: "lc_imgs"  # 左相机图像文件夹路径
image_format: ".jpg"  # 左相机图像格式（可选：.jpg 或 .png）
