# 左相机标定配置
chessboard:
  size: [11, 8]  # 棋盘格行列数
  square_size: 0.015  # 每个格子的物理尺寸（单位：米，1cm）

camera: # 单位：毫米，需要转化为米
  sensor0: 
    type: 'DEPTH'
    Translation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    Rotation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    matrix:
      fx: 545.046728971962693
      fy: 510.000000000000000
      cx: 534.957943925233735
      cy: 360.000000000000000
    distortion_coeffs: [0.00000 , 0.00000 , 0.00000 , 0.00000 , 0.00000]

  sensor1:
    type: 'DEPTH'
    Translation: [25.11685221324633587869 , 0.00000000000022069607 , 0.00000000000017849611]
    Rotation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    matrix:
      fx: 545.046728971962693
      fy: 510.000000000000000
      cx: 534.957943925233735
      cy: 360.000000000000000
    distortion_coeffs: [0.00000 , 0.00000 , 0.00000 , 0.00000 , 0.00000]

  sensor2:
    type: 'RGB'
    Translation: [50.24764065403758905859 , -0.27595258963568952693 , 2.10539648274895885294]
    Rotation: [0.00000000000000000000 , 0.00000000000000000000 , 0.00000000000000000000]
    matrix:
      fx: 776.847377473825986  # 焦距 fx
      fy: 776.847377473825986  # 焦距 fy
      cx: 780.077427821522292  # 主点 cx
      cy: 580.702099737532762  # 主点 cy
    distortion_coeffs: [0.00000, 0.000000, 0.00000, 0.00000, 0.00000]  # 畸变系数（假设无畸变）